### ISSUE TITLE
when using --modern on build prerenders all routes twice

### ISSUE THREAD

**Issue by jamiecarter7** [SolarLiner/vue-cli-plugin-prerender-spa#23] opened 2019-01-27 19:08 UTC
**Describe the bug**
Using --modern on the build function means that vue cli runs the prerender method twice, once after legacy build and again after modern build, doubling build time.

Is it necessary to do this? 

Are the rendered files different, either way I imagine they are overwritten by the second render.

**To Reproduce**
pacakge.json
```json
"scripts": {
    "build": "vue-cli-service build --modern"
 }
```

`npm run build`

**Expected behavior**
Should run the prerender only once.

**Additional context**
vue-cli-plugin-prerender-spa: ^1.1.3
vue: ^2.5.22
vue-cli: ^3.3.1

**Comment by SolarLiner** [comment] 2019-02-08 17:53
So when using the modern build Vue adds two script tags, one with the modern JS files and the other one with the "legacy" JS code, and sets the appropriate tags so that each browser loads the one it supports. In theory, there shouldn't be any overwriting done since the contents are the same. I don't know why the pre-rendering is done twice, this must be a bug on the Vue CLI part.

I'm transferring this and see what they think about it.

**Comment by SolarLiner** [comment] 2019-02-08 18:00
Okay, I can reproduce, and it looks like everything is fine. It's actually very relevant for Vue CLI to trigger plugins twice in a modern build, since some plugins might want to act on the legacy or modern build (and we don't do that since we act on the HTML). While a bit of a time waster, I don't think anything can be done from our end.

Closing this.

**Closed by SolarLiner** 2019-02-08 18:00 UTC
Labels: invalid, wontfix
